#!/bin/bash
for x in {1..120}
do
	./separator random 12
done
for x in {1..120}
do
	./separator random 13
done
for x in {1..120}
do
	./separator random 14
done
for x in {1..120}
do
	./separator random 15
done

