#!/bin/bash
for x in {1..120}
do
	./separator random 8
done
for x in {1..120}
do
	./separator random 9
done
for x in {1..120}
do
	./separator random 10
done
for x in {1..120}
do
	./separator random 11
done

